# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Name
  config.vm.hostname = "cloudinfra-osm"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  # Determine disk size (GB):
  # OSM: 40
  config.disksize.size = "40GB"

  # Plugins
  required_plugins = %w( vagrant-vbguest vagrant-disksize )
  _retry = false
  required_plugins.each do |plugin|
      unless Vagrant.has_plugin? plugin
          system "vagrant plugin install #{plugin}"
          _retry=true
      end
  end
  if (_retry)
      exec "vagrant " + ARGV.join(' ')
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  ## GUI
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  ## Grafana UI
  #config.vm.network "forwarded_port", guest: 3000, host: 3000
  ## Prometheus TSDB UI
  #config.vm.network "forwarded_port", guest: 9091, host: 9091

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # Vagrant access network
  host_ip = "192.168.33.111"
  config.vm.network "private_network", ip: "#{host_ip}", netmask: "255.255.255.0"
  ## Data network
  host_data_ip = "10.10.10.111"
  config.vm.network "private_network", ip: "#{host_data_ip}", netmask: "255.255.255.0"
  # Management network
  host_mgmt_ip = "10.10.20.111"
  config.vm.network "private_network", ip: "#{host_mgmt_ip}", netmask: "255.255.255.0"
  # Access network
  host_acce_ip = "10.10.30.111"
  config.vm.network "private_network", ip: "#{host_acce_ip}", netmask: "255.255.255.0"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Name shown in the GUI
      vb.name = "cloudinfra-osm"

  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
      vb.gui = false
  #
  #   # Customize the amount of memory on the VM (MB):
  #   # OSM: 6144-8192
    vb.memory = "6144"
  #
  #   # Customize the amount of CPUs:
  #   # OSM: 2
    vb.cpus = "2"
  #
  #   # This is commented out until resolution has been found for proper
  #   # usage. For now it will use the default graphics controller.
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    #vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    ###vb.customize ["modifyvm", :id, "--natnet1", "192.168.33/24"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
 
  # Copy files for the course at user's home
  config.vm.provision "file", source: "resources/doc/README.md", destination: "~/"
  config.vm.provision "file", source: "resources/script/operation", destination: "~/scripts"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", before: :all, privileged: false, path: "resources/script/setup/install_osm.sh"
  config.vm.provision "shell", privileged: false, path: "resources/script/setup/download_etsi_packages.sh"
  config.vm.provision "shell", after: :all, privileged: false, path: "resources/script/setup/set_permissions.sh"

  # Post-up message
  $post_up_msg = <<MSG
--------------------------------------------------------
OSM release TEN

Dashboard:      http://#{host_ip}:80
Monitoring:     http://#{host_ip}:3000
Username:       admin
Password:       admin
--------------------------------------------------------
MSG
  config.vm.post_up_message = $post_up_msg
end
